# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-18 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('salary', models.IntegerField()),
                ('created_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JobRequests',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_by', models.CharField(blank=True, max_length=100, null=True)),
                ('request_at', models.DateTimeField(auto_now_add=True)),
                ('request_on', models.ManyToManyField(blank=True, to='jobs.Job')),
            ],
        ),
    ]
